import './src/styles/global.scss'
import './src/styles/navbar.scss'
import './src/styles/footer.scss'
import './src/styles/index.scss'
import './src/styles/rooms.scss'
import './src/styles/restaurant.scss'
import './src/styles/services-and-activities.scss'
